# redirect to spanish or german landing

[[redirects]]
  from = "/"
  to = "/de"
  status = 302
  force = true
  conditions = {Language = ["de"]}

[[redirects]]
  from = "/"
  to = "/es"
  status = 302
  force = true

# redirect the 404 pages to your specific variant.

[[redirects]]
  from = "/de/*"
  to = "/de/404"
  status = 404

[[redirects]]
  from = "/es/*"
  to = "/es/404"
  status = 404


[[plugins]]
  package = "netlify-plugin-11ty"
  [plugins.inputs]
    cache_img = './assets/images'
    cache_img_httpHeader = false


[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [ ".cache" ]


[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]

	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "https://www.fundaciongoethe.org"

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"

	# Enabled providers to submit sitemap to (optional, default = 'google', 'bing', 'yandex'). Possible providers are currently only 'google', 'bing', 'yandex'.
	providers = [
		"google",
		"bing",
		"yandex"
	]

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  # Directory (relative to root of your repo) that contains the deploy-ready
  # HTML files and assets generated by the build. If a base directory has
  # been specified, include it in the publish directory path.
  publish = "dist"

  # Default build command.
  command = "npm run build"

[[headers]]
    for = "/*"
    [headers.values]
    Content-Security-Policy = "default-src 'self' www.fundaciongoethe.org api.netlify.com identity.netlify.com www.youtube-nocookie.com; connect-src 'self' www.netlifystatus.com plausible.io; img-src i.ytimg.com 'self' data: cdnjs.cloudflare.com; manifest-src 'self'; style-src 'self' fonts.googleapis.com 'unsafe-inline'; script-src 'self' data: cdnjs.cloudflare.com identity.netlify.com unpkg.com plausible.io instant.page 'unsafe-eval' 'unsafe-inline'; worker-src 'self' blob; font-src 'self' data: fonts.gstatic.com;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "autoplay=(), camera=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), publickey-credentials-get=()"