module.exports = {
  siteURL: process.env.URL || 'http://localhost:8080',
  siteName: 'Fundación Goethe',
  siteType: 'Organization', // schema
  logoUrl: 'https://www.fundaciongoethe.org/assets/svg/logo-goethe20-RGB.svg',
  siteImage: '/assets/images/social/default.jpg',
  authorName: 'Fundación Goethe',
  authorURL: 'https://www.fundaciongoethe.org',
  authorEmail: 'info@fundaciongoethe.org',
  twitterSite: '@fundaciongoethe',
  twitterCreator: '@lenesaile',
  address: {
    firma: 'Fundación Goethe',
    street: 'Calle de Almagro, 9 ',
    city: 'Madrid',
    state: 'Madrid',
    zip: '28010',
    // phoneDisplay: '+34 910 291 992',
    // phoneCall: ' +34910291992',
    mobileDisplay: '+34 670 588 264',
    mobileCall: ' +34670588264',
    email: 'info@fundaciongoethe.org',
    cif: 'G83131854',
  },
  defaultLang: 'es',
  languages: [
    {
      label: 'ES',
      code: 'es',
      long: 'Español',
      localeCode: 'es_ES',
    },
    {
      label: 'DE',
      code: 'de',
      long: 'Deutsch',
      localeCode: 'de_DE',
    },
  ],
  es: {
    localeCode: 'es_ES',
    metaTitle: 'Fundación Goethe España',
    metaDescription:
      'La Fundación Goethe reúne empresas y empresarios con el fin de promover las relaciones hispano-alemanes a nivel cultural, social, empresarial, económico.',
    back: 'Atrás',
    skipText: 'Saltar al contenido principal',
    menuButton: 'Menú',
    menuText: 'Abrir menú principal',
    menuClose: 'cerrar',
    invitations: 'Recibe invitaciones',
    invitationsLink: 'invitaciones',
    readingText: 'leer',
    sponsorSince: 'Promotor de la Fundación Goethe desde',
    sponsorCoop: 'Colaobración especial',
    sponsorCoopContent:
      'Todos nuestros promotores apoyan los eventos de la Fundación Goethe con una aportación anual. Además, existe la posibilidad de colaborar con eventos individuales por separado mediante contribuciones de patrocinio u otros servicios, por ejemplo de carácter logístico o culinario.',
    newsTitle: 'Noticias',
    newsExcerpt:
      '	En nuestra sección de noticias damos una revisión de los eventos pasados y llamamos la atención sobre eventos especiales.',
    seoArtist: 'Archivo de artistas de la Fundación Goethe',
    event: {
      artist: 'Artista',
      venue: 'Lugar',
      city: 'Ciudad',
      readmore: 'Más información',
      type: 'Tipo de evento',
      date: 'Fecha',
      duration: 'Duración',
      start: 'Comienzo',
      entry: 'Apertura de puerta',
      ending: 'Fin',
      addCalendar: 'Añade este evento a tu calendario',
      finished: 'Este evento ya ha terminado',
      finishedExtended: 'Tuvo lugar el',
      finishedPrep: 'en',
      thanks: 'Gracias por la colaboración',
      cancelled: 'Cancelado',
      deadline: 'Plazo de inscripción',
      program: 'Programa (PDF)',
      programExtra: 'Programa adicional',
      register: 'Inscríbete para participar',
      sale: 'Entradas',
      noEvent:
        'Nuestros próximos eventos están en fase de planificación, pero aún no figuran en nuestra página web. Por favor, ¡vuelve pronto!',
    },
    contact: {
      title: 'Escríbenos usando nuestro formulario',
      text: 'Si nos escribes un mensaje mediante el formulario de contacto, utilizarémos los datos que nos proporciones para mantener correspondencia contigo. ',
      firstname: 'Nombre',
      lastname: 'Apellidos',
      email: 'Email ',
      phone: 'Teléfono',
      message: 'Tu mensaje',
      optional: 'opcional',
      required: 'requerido',
      send: 'enviar',
      actionLink: 'gracias',
      creditMade: 'Hecho con',
      creditBy: 'por',
      info: 'La Fundación Goethe te informa que tratará los datos personales que facilites con la finalidad de gestionar tu consulta y darte respuesta. Puedes ejercer tus derechos de protección de datos a través del e-mail [info@fundaciongoethe.org](info@fundaciongoethe.org). Para más información, por favor, consulte nuestra [Política de Privacidad.](/es/privacidad/)',
      datos: 'He leído la política de privacidad',
    },
    newsletter: {
      language: 'Idioma de los emails',
      spanish: 'Español',
      german: 'Alemán',
      venues: 'Lugares',
      allInvitations: 'Todas las invitaciones',
      datos: 'Consiento recibir información sobre las actividades de la Fundación Goethe.',
    },
    gallery: 'Galería',
    sponsorlist: {
      title: 'Nuestros Promotores',
      regular: 'Promotores',
      premium: 'Promotores Premium',
      text: 'Nuestros promotores son, sin duda alguna, el eje central de la Fundación Goethe. Tenemos la suerte de contar desde hace años con la colaboración de reconocidas marcas de gran prestigio mundial.',
    },
    ordering: {
      orderBy: 'Ordenar por',
      city: 'Ciudad (A-Z)',
      namePlace: 'Lugar (A-Z)',
      nameArtist: 'Nombre (A-Z)',
      random: 'Aleatorio',
      type: 'Ocupación (A-Z)',
    },
    cta: {
      mainText: 'Forma parte de la Fundación Goethe como Promotor',
      subText: '...o bien promociona eventos puntuales bajo tu patrocinio.',
      btnText: 'Informate de las opciones.',
      btnLink: '/es/participar/',
    },
    cta2: {
      title: '¿Quieres mantenerte al tanto de futuros eventos?',
      text: 'Suscríbete a nuestro boletín para recibir invitaciones por correo electrónico. En los correos electrónicos recibirás información sobre los eventos planeados así como un enlace para la inscripción directa. No se llevarán a cabo medidas de publicidad.',
      btnText: 'Recibir invitaciones',
      btnLink: '/es/invitaciones/',
      image: './src/assets/images/cta/concert2.jpg',
      alt: 'Konzert im Palacio Real',
    },
  },

  de: {
    localeCode: 'de_DE',
    metaTitle: 'Fundación Goethe Spanien',
    metaDescription:
      'Wir fördern die spanisch-deutschen Beziehungen kulturell, sozial, gesellschaftlich, unternehmerisch und wirtschaftlich.',
    back: 'Zurück',
    skipText: 'Zum Hauptinhalt springen',
    menuButton: 'Menü',
    menuText: 'Hauptmenü öffnen',
    menuClose: 'Menü',
    invitations: 'Einladungen erhalten',
    invitationsLink: 'einladungen',
    readingText: 'weiterlesen',
    sponsorSince: 'Förderer der Fundación Goethe seit',
    sponsorCoop: 'Besondere Kooperation',
    sponsorCoopContent:
      'Alle unsere Förderer unterstützen die Veranstaltungen der Fundación Goethe mit einem jährlichen Beitrag. Darüber hinaus besteht die Möglichkeit, einzelne Events separat mit Sponsoringbeiträgen oder anderen Leistungen, z.B. logistischen oder kulinarischen Services, zu unterstützen.',
    newsTitle: 'Aktuelles',
    newsExcerpt:
      'In unserer Nachrichtensektion geben wir einen Rückblick auf vergangene Veranstaltungen und machen auf besondere Events aufmerksam.',
    seoArtist: 'Künstlerarchiv der Fundación Goethe',
    event: {
      artist: 'Künstler*in',
      venue: 'Veranstaltungsort',
      city: 'Stadt',
      readmore: 'Mehr erfahren',
      type: 'Art des Events',
      date: 'Datum',
      duration: 'Dauer',
      start: 'Beginn',
      entry: 'Einlass',
      ending: 'Ende',
      addCalendar: 'Vermerken Sie diese Veranstaltung in Ihrem Kalender',
      finished: 'Diese Veranstaltung ist bereits beendet',
      finishedExtended: 'Der Event fand statt am',
      finishedPrep: 'in',
      thanks: 'Danke für die besondere Kooperation',
      cancelled: 'Abgesagt',
      deadline: 'Anmeldeschluss',
      program: 'Programm (PDF)',
      programExtra: 'Programm (Zusatz) (PDF)',
      register: 'Direkt anmelden',
      sale: 'Eintrittskarten',
      noEvent:
        'Unsere nächsten Veranstaltungen sind in Planung, aber noch nicht auf unserer Webseite eingetragen. Bitte schauen Sie bald wieder rein!',
    },
    contact: {
      title: 'Schreiben Sie uns über unser Kontaktformular.',
      text: 'Wenn Sie das Kontaktformular nutzen, verwenden wir die von Ihnen angegebenen Daten, um mit Ihnen zu korrespondieren. ',
      firstname: 'Vorname',
      lastname: 'Nachname',
      email: 'E-Mail',
      phone: 'Telefon',
      message: 'Ihre Nachricht',
      optional: 'optional',
      required: 'erforderlich',
      send: 'senden',
      actionLink: 'danke',
      creditMade: 'Gemacht mit',
      creditBy: 'von',
      info: 'Die Fundación Goethe informiert Sie darüber, dass sie die von Ihnen angegebenen personenbezogenen Daten zum Zwecke der Bearbeitung Ihrer Anfrage und der Beantwortung Ihrer Anfrage verarbeiten wird. Sie können Ihre Datenschutzrechte wahrnehmen, indem Sie eine E-Mail an [info@fundaciongoethe.org](info@fundaciongoethe.org) senden. Weitere Informationen finden Sie in unserer [Datenschutzrichtlinie](/de/datenschutz/).',
      datos: 'Ich habe die Datenschutzerklärung zur Kenntnis genommen',
    },
    newsletter: {
      language: 'Sprache der E-Mails',
      spanish: 'Spanisch',
      german: 'Deutsch',
      venues: 'Orte',
      allInvitations: 'Einladungen für alle Orte',
      datos: 'Ich bin damit einverstanden, Informationen über die Aktivitäten der Fundación Goethe zu erhalten.',
    },
    gallery: 'Galerie',
    sponsorlist: {
      title: 'Unsere Förderer',
      regular: 'Förderer',
      premium: 'Förderer Premium',
      text: 'Unsere Förderer sind die zentrale Achse der Fundación Goethe. Wir haben das große Glück, seit Jahren auf die Zusammenarbeit mit weltbekannten Unternehmen zählen zu können.',
    },
    ordering: {
      orderBy: 'Sortieren nach',
      city: 'Stadt (A-Z)',
      namePlace: 'Ortsname (A-Z)',
      nameArtist: 'Name (A-Z)',
      random: 'Zufall',
      type: 'Kunstart (A-Z)',
    },
    cta: {
      mainText: 'Werden Sie Teil der Fundación Goethe als Förderer',
      subText: '...oder bewerben Sie einzelne Veranstaltungen unter Ihrer Schirmherrschaft!',
      btnText: 'Alle Möglichkeiten kennenlernen',
      btnLink: '/de/mitmachen/',
    },
    cta2: {
      title: 'Möchten Sie über zukünftige Veranstaltungen informiert werden?',
      text: 'Abonnieren Sie unseren Newsletter, um Einladungen per E-Mail zu erhalten. In den E-Mails erhalten Sie Informationen zu ausgewählten Veranstaltungen sowie einen Link zur direkten Anmeldung. Es werden keine Werbemaßnahmen durchgeführt.',
      btnText: 'Einladungen erhalten',
      btnLink: '/de/einladungen/',
      image: './src/assets/images/cta/concert2.jpg',
      alt: 'Konzert im Palacio Real',
    },
  },

  isProduction: process.env.ELEVENTY_ENV === 'production',
};
