module.exports = {
	siteURL: process.env.URL || "http://localhost:8080",
	siteName: "Fundación Goethe",
	siteType: "Organization", // schema
	siteImage: "/assets/images/default.png",
	authorName: "Fundación Goethe",
	authorURL: "https://www.fundaciongoethe.org",
	authorEmail: "info@fundaciongoethe.org",
	twitterSite: "@fundaciongoethe",
	twitterCreator: "@lenesaile",
	address: {
		firma: "Fundación Goethe",
		street: "Calle de Almagro, 9 ",
		city: "Madrid",
		state: "Madrid",
		zip: "28010",
		phoneDisplay: "+34 910 291 992",
		phoneCall: " +34910291992",
		mobileDisplay: "+34 670 588 264",
		mobileCall: " +34670588264",
		email: "info@fundaciongoethe.org",
	},
	defaultLang: "es",
	languages: [
		{
			label: "ES",
			code: "es",
			long: "Español",
			localeCode: "es_ES",
		},
		{
			label: "DE",
			code: "de",
			long: "Deutsch",
			localeCode: "de_DE",
		},
	],
	es: {
		metaTitle: "Fundación Goethe España",
		metaDescription:
			"La Fundación Goethe reúne empresas y empresarios con el fin de promover las relaciones hispano-alemanes a nivel cultural, social, empresarial, económico.",
		back: "Atrás",
		skipText: "Saltar al contenido principal",
		menuButton: "Menú",
		menuText: "Abrir menú principal",
		menuClose: "cerrar",
		invitations: "Recibe invitaciones",
		readingText: "seguir leyendo",
		sponsorSince: "Patrocinador de la Fundación Goethe desde",
		sponsorCoop: "Colaobración especial",
		sponsorCoopContent:
			"Todos nuestros patrocinadores apoyan los eventos de la Fundación Goethe con una aportación anual. Además, existe la posibilidad de colaborar con eventos individuales por separado mediante contribuciones de patrocinio u otros servicios, por ejemplo de carácter logístico o culinario.",
		newsTitle: "Noticias",
		newsExcerpt:
			"	En nuestra sección de noticias damos una revisión de los eventos pasados y llamamos la atención sobre eventos especiales.",
		seoArtist: "Archivo de artistas de la Fundación Goethe",
		event: {
			artist: "Artista",
			venue: "Lugar",
			readmore: "Más sobre",
			type: "Tipo de evento",
			date: "Fecha",
			duration: "Duración",
			start: "Comienzo",
			entry: "Apertura de puerta",
			addCalendar: "Añade este evento a tu calendario",
			finished: "Este evento ya ha terminado",
			thanks: "Gracias por la colaboración",
		},
	},
	de: {
		metaTitle: "Fundación Goethe Spanien",
		metaDescription:
			"Wir fördern die spanisch-deutschen Beziehungen kulturell, sozial, gesellschaftlich, unternehmerisch und wirtschaftlich.",
		back: "Zurück",
		skipText: "Zum Hauptinhalt springen",
		menuButton: "Menü",
		menuText: "Hauptmenü öffnen",
		menuClose: "Menü",
		invitations: "Einladungen erhalten",
		readingText: "weiterlesen",
		sponsorSince: "Förderer der Fundación Goethe seit",
		sponsorCoop: "Besondere Kooperation",
		sponsorCoopContent:
			"Alle unsere Förderer unterstützen die Veranstaltungen der Fundación Goethe mit einem jährlichen Beitrag. Darüber hinaus besteht die Möglichkeit, einzelne Events separat mit Sponsoringbeiträgen oder anderen Leistungen, z.B. logistischen oder kulinarischen Services, zu unterstützen.",
		newsTitle: "Aktuelles",
		newsExcerpt:
			"	In unserer Nachrichtensektion geben wir einen Rückblick auf vergangene Veranstaltungen und machen auf besondere Events aufmerksam.",
		seoArtist: "Künstlerarchiv der Fundación Goethe",
		event: {
			artist: "Künstler/in",
			venue: "Ort",
			readmore: "Mehr über",
			type: "Art des Events",
			date: "Datum",
			duration: "Dauer",
			start: "Beginn",
			entry: "Einlass",
			addCalendar: "Fügen Sie diese Veranstaltung zu Ihrem Kalender hinzu",
			finished: "Diese Veranstaltung ist bereits beendet",
			thanks: "Danke für die besondere Kooperation",
		},
	},

	isProduction: process.env.ELEVENTY_ENV === "production",
};
