module.exports = {
  siteURL: process.env.URL || 'http://localhost:8080',
  siteName: 'Fundación Goethe',
  siteType: 'Organization', // schema
  logoUrl: 'https://www.fundaciongoethe.org/assets/svg/logo-goethe20-RGB.svg',
  siteImage: '/assets/images/default.png',
  authorName: 'Fundación Goethe',
  authorURL: 'https://www.fundaciongoethe.org',
  authorEmail: 'info@fundaciongoethe.org',
  twitterSite: '@fundaciongoethe',
  twitterCreator: '@lenesaile',
  address: {
    firma: 'Fundación Goethe',
    street: 'Calle de Almagro, 9 ',
    city: 'Madrid',
    state: 'Madrid',
    zip: '28010',
    phoneDisplay: '+34 910 291 992',
    phoneCall: ' +34910291992',
    mobileDisplay: '+34 670 588 264',
    mobileCall: ' +34670588264',
    email: 'info@fundaciongoethe.org',
    cif: 'G83131854',
  },
  defaultLang: 'es',
  languages: [
    {
      label: 'ES',
      code: 'es',
      long: 'Español',
      localeCode: 'es_ES',
    },
    {
      label: 'DE',
      code: 'de',
      long: 'Deutsch',
      localeCode: 'de_DE',
    },
  ],
  es: {
    localeCode: 'es_ES',
    metaTitle: 'Fundación Goethe España',
    metaDescription:
      'La Fundación Goethe reúne empresas y empresarios con el fin de promover las relaciones hispano-alemanes a nivel cultural, social, empresarial, económico.',
    back: 'Atrás',
    skipText: 'Saltar al contenido principal',
    menuButton: 'Menú',
    menuText: 'Abrir menú principal',
    menuClose: 'cerrar',
    invitations: 'Recibe invitaciones',
    invitationsLink: 'invitaciones',
    readingText: 'leer',
    sponsorSince: 'Patrocinador de la Fundación Goethe desde',
    sponsorCoop: 'Colaobración especial',
    sponsorCoopContent:
      'Todos nuestros patrocinadores apoyan los eventos de la Fundación Goethe con una aportación anual. Además, existe la posibilidad de colaborar con eventos individuales por separado mediante contribuciones de patrocinio u otros servicios, por ejemplo de carácter logístico o culinario.',
    newsTitle: 'Noticias',
    newsExcerpt:
      '	En nuestra sección de noticias damos una revisión de los eventos pasados y llamamos la atención sobre eventos especiales.',
    seoArtist: 'Archivo de artistas de la Fundación Goethe',
    event: {
      artist: 'Artista',
      venue: 'Lugar',
      readmore: 'Más sobre',
      type: 'Tipo de evento',
      date: 'Fecha',
      duration: 'Duración',
      start: 'Comienzo',
      entry: 'Apertura de puerta',
      ending: 'Fin',
      addCalendar: 'Añade este evento a tu calendario',
      finished: 'Este evento ya ha terminado',
      finishedExtended: 'Tuvo lugar el',
      finishedPrep: 'en',
      thanks: 'Gracias por la colaboración',
      visitWeb: 'Visita el sitio web de',
      deadline: 'Plazo de inscripción',
      program: 'Descargar programa (PDF)',
      register: 'Inscríbete para participar',
      sale: 'Comprar entradas',
    },
    contact: {
      title: 'Escríbenos usando nuestro formulario',
      text: 'Si nos escribes un mensaje mediante el formulario de contacto, utilizarémos los datos que nos proporciones para mantener correspondencia contigo. ',
      firstname: 'Nombre',
      lastname: 'Apellidos',
      email: 'Email ',
      phone: 'Teléfono',
      message: 'Tu mensaje',
      optional: 'opcional',
      required: 'requerido',
      send: 'enviar',
      actionLink: 'gracias',
      creditMade: 'Hecho con',
      creditBy: 'por',
    },
    newsletter: {
      language: 'Idioma de los emails',
      spanish: 'Español',
      german: 'Alemán',
      venues: 'Lugares',
      allInvitations: 'Todas las invitaciones',
      datos: 'He leído la política de privacidad y acepto recibir invitaciones por correo electrónico.',
    },
    gallery: 'Galería',
  },
  de: {
    localeCode: 'de_DE',
    metaTitle: 'Fundación Goethe Spanien',
    metaDescription:
      'Wir fördern die spanisch-deutschen Beziehungen kulturell, sozial, gesellschaftlich, unternehmerisch und wirtschaftlich.',
    back: 'Zurück',
    skipText: 'Zum Hauptinhalt springen',
    menuButton: 'Menü',
    menuText: 'Hauptmenü öffnen',
    menuClose: 'Menü',
    invitations: 'Einladungen erhalten',
    invitationsLink: 'einladungen',
    readingText: 'weiterlesen',
    sponsorSince: 'Förderer der Fundación Goethe seit',
    sponsorCoop: 'Besondere Kooperation',
    sponsorCoopContent:
      'Alle unsere Förderer unterstützen die Veranstaltungen der Fundación Goethe mit einem jährlichen Beitrag. Darüber hinaus besteht die Möglichkeit, einzelne Events separat mit Sponsoringbeiträgen oder anderen Leistungen, z.B. logistischen oder kulinarischen Services, zu unterstützen.',
    newsTitle: 'Aktuelles',
    newsExcerpt:
      'In unserer Nachrichtensektion geben wir einen Rückblick auf vergangene Veranstaltungen und machen auf besondere Events aufmerksam.',
    seoArtist: 'Künstlerarchiv der Fundación Goethe',
    event: {
      artist: 'Künstler*in',
      venue: 'Ort',
      readmore: 'Mehr über',
      type: 'Art des Events',
      date: 'Datum',
      duration: 'Dauer',
      start: 'Beginn',
      entry: 'Einlass',
      ending: 'Ende',
      addCalendar: 'Vermerken Sie diese Veranstaltung in Ihrem Kalender',
      finished: 'Diese Veranstaltung ist bereits beendet',
      finishedExtended: 'Der Event fand statt am',
      finishedPrep: 'in',
      thanks: 'Danke für die besondere Kooperation',
      visitWeb: 'Besuche die Webseite von',
      deadline: 'Anmeldeschluss',
      program: 'Programm  herunterladen (PDF)',
      register: 'Direkt anmelden',
      sale: 'Eintrittskarten kaufen',
    },
    contact: {
      title: 'Schreiben Sie uns über unser Kontaktformular.',
      text: 'Wenn Sie das Kontaktformular nutzen, verwenden wir die von Ihnen angegebenen Daten, um mit Ihnen zu korrespondieren. ',
      firstname: 'Vorname',
      lastname: 'Nachname',
      email: 'E-Mail',
      phone: 'Telefon',
      message: 'Ihre Nachricht',
      optional: 'optional',
      required: 'erforderlich',
      send: 'senden',
      actionLink: 'danke',
      creditMade: 'Gemacht mit',
      creditBy: 'von',
    },
    newsletter: {
      language: 'Sprache der E-Mails',
      spanish: 'Spanisch',
      german: 'Deutsch',
      venues: 'Orte',
      allInvitations: 'Einladungen für alle Orte',
      datos:
        'Ich habe die Datenschutzerklärung zur Kenntnis genommen und bin damit einverstanden, per E-Mail Einladungen zu erhalten.',
    },
    gallery: 'Galerie',
  },

  isProduction: process.env.ELEVENTY_ENV === 'production',
};
